# Generated by Django 3.1.5 on 2021-02-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210208_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
