# Generated by Django 3.0.5 on 2021-03-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210331_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='user',
            new_name='userrider',
        ),
    ]
