# Generated by Django 3.1.5 on 2021-01-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='type_vehicle',
            field=models.CharField(default='', max_length=45),
        ),
    ]
