# Generated by Django 3.1.5 on 2021-02-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210208_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='id_product',
        ),
        migrations.AddField(
            model_name='product',
            name='id_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
    ]
