# Generated by Django 3.1.5 on 2021-02-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210208_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.restaurant'),
        ),
    ]
