# Generated by Django 3.1.5 on 2021-01-22 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rider_type_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=50, unique=True)),
                ('preparado', models.BooleanField(default=False)),
                ('image_idImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('riders', models.ManyToManyField(to='api.Rider')),
            ],
        ),
    ]
