# Generated by Django 3.0.5 on 2021-04-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210331_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_pedido', to='api.Pedido'),
        ),
    ]
