# Generated by Django 3.1.5 on 2021-01-21 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210121_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='id_image',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_order',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_pedido',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='id_restaurant',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='id_rider',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_user',
            new_name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='estado',
            field=models.CharField(default='', max_length=45),
        ),
    ]
