# Generated by Django 3.1.5 on 2021-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210210_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='', max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='postalcode',
            field=models.CharField(default='', max_length=5),
        ),
    ]
