# Generated by Django 3.0.5 on 2021-04-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210402_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.Pedido'),
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='restaurants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosrestaurant', to='api.Restaurant'),
        ),
    ]
