# Generated by Django 3.0.5 on 2021-04-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210402_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='api.Product'),
        ),
    ]
