# Generated by Django 3.1.5 on 2021-01-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210122_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rider_idRider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rider'),
        ),
    ]
