# Generated by Django 3.1.5 on 2021-01-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210121_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_has_rider',
            name='Restaurant_idRestaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant_has_rider',
            name='Rider_idRider',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='restaurants',
            field=models.ManyToManyField(to='api.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='riders',
            field=models.ManyToManyField(to='api.Rider'),
        ),
        migrations.DeleteModel(
            name='Restaurant_has_Pedido',
        ),
        migrations.DeleteModel(
            name='Restaurant_has_Rider',
        ),
    ]
