# Generated by Django 3.1.5 on 2021-02-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_restaurant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_restaurant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.restaurant'),
        ),
    ]
