# Generated by Django 3.1.5 on 2021-02-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210216_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rider'),
        ),
    ]
