# Generated by Django 3.1.5 on 2021-05-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210517_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
