# Generated by Django 3.1.5 on 2021-01-22 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210122_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('image_idImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
                ('restaurants', models.ManyToManyField(to='api.Restaurant')),
            ],
        ),
    ]
