# Generated by Django 3.2.3 on 2021-05-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_restaurant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosrider', to='api.rider'),
        ),
    ]
