# Generated by Django 3.1.5 on 2021-02-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210220_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='num_pedido',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
