# Generated by Django 3.1.5 on 2021-01-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('preparado', 'Preparado'), ('entregado', 'Entregado'), ('en concina', 'Cocinando'), ('recibida la solicitud de pedido', 'Recibido')], default='recibida la solicitud de pedido', max_length=45),
        ),
    ]
