# Generated by Django 3.1.5 on 2021-03-18 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210220_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='entregado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='num_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='restaurants',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidouser', to='api.pedido'),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('num_pedidos', models.PositiveBigIntegerField(default=0, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entregado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('preparado', 'Preparado'), ('entregado', 'Entregado'), ('en concina', 'Cocinando'), ('recibida la solicitud de pedido', 'Recibido')], default='recibida la solicitud de pedido', max_length=45)),
                ('pagado', models.BooleanField(default=False)),
                ('restaurants', models.ManyToManyField(related_name='pedidosrestaurant', to='api.Restaurant')),
                ('rider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidosrider', to='api.rider')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedidos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.pedidos'),
        ),
    ]
