# Generated by Django 3.1.5 on 2021-01-23 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rider_libre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('image_idImage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='image_idImage',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='name',
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('preparado', 'Preparado'), ('entregado', 'Entregado'), ('en concina', 'Cocinando'), ('recibida la solicitud de pedido', 'Recibido')], default='recibida la solicitud de pedido', max_length=45),
        ),
        migrations.AddField(
            model_name='pedido',
            name='num_pedido',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
