# Generated by Django 3.1.5 on 2021-01-23 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Rider',
        ),
        migrations.AddField(
            model_name='user',
            name='rider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rider'),
        ),
    ]
