# Generated by Django 3.1.5 on 2021-01-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210123_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='rider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rider'),
        ),
    ]
