# Generated by Django 3.1.5 on 2021-01-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_pedido_rider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='image_idImage',
            new_name='image',
        ),
    ]
