# Generated by Django 3.1.5 on 2021-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210123_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_idImage',
            new_name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
