# Generated by Django 3.1.5 on 2021-02-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210202_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='preparado',
        ),
    ]
