# Generated by Django 3.1.5 on 2021-02-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210203_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='restaurant',
            new_name='id_restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='riders',
        ),
    ]
