# Generated by Django 3.1.5 on 2021-02-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210203_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='product',
            new_name='id_product',
        ),
    ]
